import test from 'node:test';import assert from 'node:assert/strict';
import {page,layer,clone} from '../src/model.js';
import {floatSelection,anchor} from '../src/raster.js';
import {clipboardPage,clipboardSelection} from '../src/clipboard.js';
function source(){return {width:2,height:1,x:3,y:4,layerId:'old',pixels:new Uint8ClampedArray([10,20,30,255,0,0,0,0]),inverted:new Uint8Array([0,1])};}
test('new page and document paste keep special pixels without aliasing clipboard',()=>{const f=source(),a=clipboardPage(f),b=clipboardPage(f);a.layers[0].pixels[0]=99;a.layers[0].inverted[1]=0;assert.equal(f.pixels[0],10);assert.equal(b.layers[0].pixels[0],10);assert.equal(f.inverted[1],1);assert.equal(b.layers[0].inverted[1],1);});
test('floating paste targets selected destination layer and clones clipboard',()=>{const p=page(2,1),f=source(),pasted=clipboardSelection(f,p);assert.equal(pasted.layerId,p.layers[0].id);assert.deepEqual([pasted.x,pasted.y],[0,0]);pasted.inverted[1]=0;assert.equal(f.inverted[1],1);p.layers[0].selected=false;assert.throws(()=>clipboardSelection(f,p),/Выберите слой/);});
test('copy resolves inversion overlap instead of ORing layer flags',()=>{const p=page(2,1);p.layers[0].inverted.fill(1);const top=layer(2,1);top.inverted[0]=1;top.pixels.set([30,40,50,255],4);p.layers.push(top);const f=floatSelection(p,false);assert.deepEqual([...f.inverted],[0,0]);assert.deepEqual([...f.pixels],[0,0,0,0,30,40,50,255]);assert.deepEqual([...p.layers[0].inverted],[1,1]);});
test('anchor clears stale inversion under opaque color and clears RGBA under inversion',()=>{const p=page(2,1);p.layers[0].inverted[0]=1;p.layers[0].pixels.set([99,88,77,255],4);p.floating=clipboardSelection(source(),p);anchor(p);assert.deepEqual([...p.layers[0].inverted],[0,1]);assert.deepEqual([...p.layers[0].pixels],[10,20,30,255,0,0,0,0]);});
test('unsupported partial-alpha anchoring rejects before any document mutation',()=>{const p=page(2,1);p.layers[0].inverted[1]=1;p.floating=clipboardSelection(source(),p);p.floating.inverted.fill(0);p.floating.pixels.set([1,2,3,128],4);const before=clone(p);assert.throws(()=>anchor(p),/без потерь/);assert.deepEqual(p,before);});
